device: "cuda"
unprocessed_data: '/scratch/smt570/SCOTUS_full/wavs/SCOTUS/*/*' #case subsection
---
data:
    main_path: '/scratch/smt570/SCOTUS_full/wavs/SCOTUS/'
    save_path: '/scratch/jt2565/SCOTUSfull_Processed/'
    verbose: !!bool "true"
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: '/SpeakerVerification/data/model.model/'
    #model_path: '/scratch/igw212/capstone/CDS-Capstone-2020/colab_diarization/model.model'  #Model path for testing, inference, or resuming training
