device: "cpu"
unprocessed_data: 'SpeakerVerificationEmbedding/data/SCOTUS/*/*' #case subsection
---
data:
    main_path: 'SpeakerVerificationEmbedding/data/SCOTUS/'
    save_path: 'SpeakerVerificationEmbedding/data/SCOTUS_Processed/'
    verbose: !!bool "true"
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: 'SpeakerVerificationEmbedding/data/model.model' #Model path for testing, inference, or resuming training
